### ISSUE TITLE
failing load models

### ISSUE THREAD

**Issue by Miorey** [Miorey/wow-model-viewer#39]
wowhead decide to change it cors policies for that reason the models are no more available 
I will fix this issue but it will take a while

**Comment by LichKing255** [comment]
confirm

**Comment by Ataxia123** [comment]
Hey any updates on this issue? i tried to use the branch with the I guess experimental fixes but couldn't get it to work. any suggestions?

**Comment by Miorey** [comment]
@Ataxia123 I will push a new version Monday or Tuesday with the fix.

**Comment by Miorey** [comment]
In the last version I explain how to bypass cors policies. Please read the documentation carefully.
I close the issue.

**Comment by Miorey** [comment]
To fix the issue you will need to store the files from zaming. To do this locally you can use my bypass cors docker image
```yml
version: '3'

services:
  bypass-cors-policies:
    image: miorey/bypass-cors-policies:v1
    environment:
      - SERVER_NAME=https://wow.zamimg.com
    volumes:
      - ./storage:/usr/src/app/storage
    ports:
      - "2999:3000"
```
in your html file change
```html
    <script src="http://localhost:2999/modelviewer/live/viewer/viewer.min.js"></script>
```
and 
```
    window.CONTENT_PATH = `http://localhost:2999/modelviewer/live/`
```
